{{- if .Values.secretEnv.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keda-scaledobject.fullname" . }}-conn
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keda-scaledobject.labels" . | nindent 4 }}
type: Opaque
stringData:
  connectionString: {{ .Values.secretEnv.connectionString | quote }}
{{- end }}
